DROP TABLE DETAIL IF EXISTS;
CREATE TABLE DETAIL (
    detailid INTEGER PRIMARY KEY NOT NULL,
    detailname VARCHAR(255) UNIQUE NOT NULL
);

DROP TABLE DOCHEAD IF EXISTS;
CREATE TABLE DOCHEAD (
    documentid INTEGER PRIMARY KEY NOT NULL,
    documenttype INTEGER NOT NULL,
    documentdate DATETIME NOT NULL
);

DROP TABLE DOCBODY IF EXISTS;
CREATE TABLE DOCBODY (
    documentid INTEGER REFERENCES DOCHEAD (documentid) NOT NULL,
    detailid INTEGER REFERENCES DETAIL (detailid) NOT NULL,
    detailcount INTEGER NOT NULL
);
