SET DATABASE SQL SYNTAX ORA TRUE;

DROP TABLE DETAIL IF EXISTS;
CREATE TABLE DETAIL (
    detailid INTEGER IDENTITY,
    detailname VARCHAR(255) NOT NULL
);

DROP TABLE DOCHEAD IF EXISTS;
CREATE TABLE DOCHEAD (
    documentid INTEGER IDENTITY,
    documenttype INTEGER NOT NULL,
    documentdate DATE NOT NULL,
    documentprice INTEGER NOT NULL
);

DROP TABLE DOCBODY IF EXISTS;
CREATE TABLE DOCBODY (
    FOREIGN KEY documentid REFERENCES DOCHEAD(documentid),
    FOREIGN KEY detailid REFERENCES DETAIL(detailid),
    detailcount INTEGER NOT NULL
);